#!/bin/bash
#
aeg=`date +%H`
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
echo "tere hommikust, $USER!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
echo "Tere paevast, $USER!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
echo "Tere ohtust, $USER!"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
echo "head ood, $USER!"
else 
echo "Vale sisned, $USER"
fi
#
