#!/bin/bash
aeg=`date +%H`
kas=$(whoami)
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
		echo "Tere hommikust, $Ukas"	
	elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then 
		echo "Tere paevast, $kas"
	elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
		echo "Tere ohtust, $kas"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
		echo -n "Head ood, $kas";
else
	echo "Vigane sisend"
fi
