#!/bin/bash
#
echo -n "sisesta külg a vaartus "
read A
echo -n "sisesta külg b vaartus "
read B
BSquared=$(($B**2))
ASquared=$(($A**2))
CSquared=$(($BSquared+$ASquared))
Hypot=$(echo "scale=2;sqrt($CSquared)"| bc)
echo "A = $A"
echo "B = $B"
echo "C = $Hypot"
#
#
